### ISSUE TITLE
Round 3

### ISSUE THREAD

**Issue by sheetalsingh08** [Abhishekmishra-17/Phenol-formaldehyde-Resin#4]
Kindly develop even a single  module in simulator so that we have something to show atleast in the closing ceremony

**Comment by Abhishekmishra-17** [comment]
we are working on that. All images and frontend HTML and JS will be uploaded in the respective folder. But some changes have to be done in the future.

**Comment by sheetalsingh08** [comment]
future changes we will keep doing , but right now we sholud have some module to show !

**Comment by Abhishekmishra-17** [comment]
All done.
